/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentsrecord;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SSM LAB
 */
public class check extends javax.swing.JFrame {

    /**
     * Creates new form check
     */
    public check() {
        setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        stdregno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDpmnt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtStdname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtMbno = new javax.swing.JTextField();
        txtRegno = new javax.swing.JTextField();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel3.setText("<-");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 40, 30));

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel4.setText("X");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, 20));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECK STUDENT DETAILS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 26, -1, 37));

        jLabel13.setBackground(new java.awt.Color(3, 138, 255));
        jLabel13.setFont(new java.awt.Font("Cantarell", 1, 36)); // NOI18N
        jLabel13.setText("-");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 20, 20));

        jPanel2.setBackground(new java.awt.Color(30, 81, 123));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Student RegNo :");
        jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel2FocusGained(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        stdregno.setBackground(new java.awt.Color(37, 41, 88));
        stdregno.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        stdregno.setForeground(new java.awt.Color(255, 255, 255));
        stdregno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdregnoActionPerformed(evt);
            }
        });
        jPanel2.add(stdregno, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 152, 30));

        jButton1.setBackground(new java.awt.Color(46, 204, 113));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Check");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 100, 30));

        txtCity.setEditable(false);
        txtCity.setBackground(new java.awt.Color(30, 81, 123));
        txtCity.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtCity.setForeground(new java.awt.Color(204, 204, 204));
        txtCity.setBorder(null);
        jPanel2.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 160, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("REGISTER NO        :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 111, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("STUDENT NAME   :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 166, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FATHER NAME      :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("MOBILE NO          :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CITY                        :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 150, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DEPARTMENT         :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("EMAIL                      :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 140, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DOB                         :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        txtDpmnt.setEditable(false);
        txtDpmnt.setBackground(new java.awt.Color(30, 81, 123));
        txtDpmnt.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtDpmnt.setForeground(new java.awt.Color(204, 204, 204));
        txtDpmnt.setAutoscrolls(false);
        txtDpmnt.setBorder(null);
        jPanel2.add(txtDpmnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 210, -1));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(30, 81, 123));
        txtEmail.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(204, 204, 204));
        txtEmail.setBorder(null);
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 220, -1));

        txtDate.setEditable(false);
        txtDate.setBackground(new java.awt.Color(30, 81, 123));
        txtDate.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(204, 204, 204));
        txtDate.setActionCommand("");
        txtDate.setAutoscrolls(false);
        txtDate.setBorder(null);
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 220, -1));

        txtStdname.setEditable(false);
        txtStdname.setBackground(new java.awt.Color(30, 81, 123));
        txtStdname.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtStdname.setForeground(new java.awt.Color(204, 204, 204));
        txtStdname.setBorder(null);
        jPanel2.add(txtStdname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, -1));

        txtFname.setEditable(false);
        txtFname.setBackground(new java.awt.Color(30, 81, 123));
        txtFname.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtFname.setForeground(new java.awt.Color(204, 204, 204));
        txtFname.setBorder(null);
        jPanel2.add(txtFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 140, -1));

        txtMbno.setEditable(false);
        txtMbno.setBackground(new java.awt.Color(30, 81, 123));
        txtMbno.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtMbno.setForeground(new java.awt.Color(204, 204, 204));
        txtMbno.setBorder(null);
        jPanel2.add(txtMbno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 140, -1));

        txtRegno.setEditable(false);
        txtRegno.setBackground(new java.awt.Color(30, 81, 123));
        txtRegno.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        txtRegno.setForeground(new java.awt.Color(204, 204, 204));
        txtRegno.setBorder(null);
        jPanel2.add(txtRegno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
           
        try {
            String rgno1=stdregno.getText();
            
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stdrecords","root","");
            String query = "select *from records where REGNO= ?";
            
            PreparedStatement gst = (PreparedStatement) con.prepareStatement(query);
          
            gst.setString(1,rgno1);
            
            ResultSet rs = gst.executeQuery();
            
            
            
            //if(rs.next()){
            
            if(rs.next())
            {           	   
                String regno = rs.getString("REGNO");
                String stdname = rs.getString("STDNAME");
                String fname = rs.getString("FATHERNAME");
                String dpt = rs.getString("DPT");
                String mobno = rs.getString("MOBNO");
                String email = rs.getString("EMAIL");
                String city = rs.getString("CITY");
                String date = rs.getString("DATE");
                            
                            txtRegno.setText(regno);
                            txtStdname.setText(stdname);
                            txtFname.setText(fname);
                            txtDpmnt.setText(dpt);
                            txtMbno.setText(mobno);
                            txtEmail.setText(email);
                            txtCity.setText(city);
                            txtDate.setText(date);    
               }else{
            
                            txtRegno.setText("");
                            txtStdname.setText("");
                            txtFname.setText("");
                            txtDpmnt.setText("");
                            txtMbno.setText("");
                            txtEmail.setText("");
                            txtCity.setText("");
                            txtDate.setText("");
                
            JOptionPane.showMessageDialog(this,"Something Error or invalid Register number!");
            
            
            }
            
        
            
            
            
          // TODO add your handling code here:
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(check.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stdregnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdregnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdregnoActionPerformed

    private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2FocusGained

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
Interface sd = new Interface();
sd.setVisible(true);
this.hide();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField stdregno;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDpmnt;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtMbno;
    private javax.swing.JTextField txtRegno;
    private javax.swing.JTextField txtStdname;
    // End of variables declaration//GEN-END:variables
}
